### PR TITLE
changes to make it work

### PR DESCRIPTION
**Pull request by bbelderbos**
This is a nice starter auction project.  

I might want to extend it so I made some changes to get it working on my system upgrading the dependencies.

Doing an PR so you can check my changes, maybe save you some work if you want to further develop this.

Cheers
Bob

### CODE REVIEW

**Comment by BhargavaRavaliKoganti** [comment]
Hey, thanks for the changes. Most of the places I have seen you replaced 'import *' to 'import specific thing'. Does this make any difference? When I say 'import *' it imports everything so, does it effect anything else? I just completed my graduation please help me in learning.

**Comment by pybites** [comment]
Yes import * is an anti pattern, bad for namespacing, less transparent where things coming from, see here: https://stackoverflow.com/questions/2386714/why-is-import-bad

Are you planning to extend this project?

**Comment by bbelderbos** [comment]
That was me ;)

**Comment by BhargavaRavaliKoganti** [comment]
ya, I would want to extend the project.

**Pull request merged**
